### ISSUE TITLE
Facultative passkey

### ISSUE THREAD

**Issue by Thalowass** [arvida42/jackettio#10]
Hi,

Could you include an option for a facultative passkey? I'm setting up an instance for a private tracker, but users without a passkey should still be able to download cached torrents.

Another idea is to grant users the ability to cache a number of torrents with my passkey.

**Comment by arvida42** [comment]
Adding the ability to stream cached private torrents without requiring a passkey is an excellent idea. This is now the default behavior without any additional configuration.

However, grant users the ability to cache torrents with your passkey is bad since it can expose your passkey to those users.
