### ISSUE TITLE
Flaresolverr

### ISSUE THREAD

**Issue by Markodingo** [arvida42/jackettio#21]
Flaresolverr has stopped working with Yggtorrent.

**Comment by arvida42** [comment]
This is a know issue on Flaresolverr: https://github.com/FlareSolverr/FlareSolverr/issues/1253

**Comment by Markodingo** [comment]
> This is a know issue on Flaresolverr: [FlareSolverr/FlareSolverr#1253](https://github.com/FlareSolverr/FlareSolverr/issues/1253)

Yes, I had seen the solution. And once again, a big thank you for your addon! 🙏
