### ISSUE TITLE
Icon for Status change - cached or not .... 

### ISSUE THREAD

**Issue by piotrasd** [arvida42/jackettio#23]
jackettio is great plugin to use with own private tracker and work pretty well 
Im just finding myself hard to find torrent which I pick to download/watch 

For short time we have small info about progress like on picture 
![image](https://github.com/user-attachments/assets/555de7e7-ab27-4c6d-a98f-455c6b3df2cf)

but later on if we back to same movie all torrent looks same with floppy disk icon 
hard to memorise which we picked before 

there is any way to update status - icon which is already cached ? 
like instead of floppy disk icon maybe use this  ✅ ?? (just to recognise this position is already cached by real-debird and ready to watch ? 

and maybe could be in results as first position ? and then later all not-cached

**Comment by arvida42** [comment]
Cached items are marked with a "+" sign (e.g., DL+, RD+, AD+).

All cached items are prioritized and appear in the first position.

**Comment by razeNFR** [comment]
![Screenshot_2024-09-07-12-10-02-76_5a1e11fa41055108da81eb54eea93a2a](https://github.com/user-attachments/assets/ca5bb1b4-dbc4-40ba-b26e-6137c0deba13)

It can be possible with a docker file, i will drop a tutorial here to do that, if you want 😊

**Comment by piotrasd** [comment]
Nice please !!

**Comment by piotrasd** [comment]
> Cached items are marked with a "+" sign (e.g., DL+, RD+, AD+).
> 
> All cached items are prioritized and appear in the first position.

I don’t see any + or are listed first, can you send screenshot ? And we speaking about public or private trackers ?

**Comment by razeNFR** [comment]
> > Cached items are marked with a "+" sign (e.g., DL+, RD+, AD+).
> > All cached items are prioritized and appear in the first position.
> 
> I don’t see any + or are listed first, can you send screenshot ? And we speaking about public or private trackers ?

Are you sure you put your api from debrider ?
