### ISSUE TITLE
Searching downloading all related torrent files ??

### ISSUE THREAD

**Issue by piotrasd** [arvida42/jackettio#25]
Hi I notice on my private tracker that, what ever im looking for (searching) through this add-on is marked on Tracker as downloaded 
is this how is work and must be like that ??

<img width="1539" alt="Screenshot 2024-09-10 at 16 10 59" src="https://github.com/user-attachments/assets/97f9538d-5c47-4bc6-8219-66d1a15e26a6">

Before I was using jackett addon with sickrage and I never had this issue.

If I'm manually searching something on Jackett then nothing is listed on tracker as downloaded (like suppose be)
only if im download specific torrent 
<img width="1374" alt="Screenshot 2024-09-10 at 16 11 15" src="https://github.com/user-attachments/assets/5531debc-3247-4b6d-8673-b42cf7e40b43">

There is any chance to fix this ?

**Comment by arvida42** [comment]
Yes, downloading the torrent file is necessary to obtain its hashstring and check if it's cached on debrid.  This process should not affect your tracker statistics.
