### ISSUE TITLE
Sorting Issue

### ISSUE THREAD

**Issue by Blissingg** [arvida42/jackettio#27]
Couldn't see an open ticket for this but sometimes results and the sorting seem to get mixed up.

Setup is self-hosted using docker.

I have Quality then Size selected and set up but sometimes on certain series/episodes it will show 1 or 2 4k results at the top a bunch of 1080p and then a couple of more 4k results followed by more 1080p results.

Screenshots attached showing settings for Jackettio and an example of the issue

![jackettio](https://github.com/user-attachments/assets/d33e564b-ac55-4a80-8709-e80387293b46)
![stremjacket](https://github.com/user-attachments/assets/6d560887-9a4c-47b0-b81a-313b93e3baa0)

**Comment by arvida42** [comment]
This is the expected behavior. Since English is prioritized, torrents detected as English will appear at the top of the list based on the correct sorting method. It's possible that some torrents should be detected as English but aren’t?
