### ISSUE TITLE
It play movies but after a while it keep loading and after a while it keep loading.

### ISSUE THREAD

**Issue by ericvlog** [arvida42/jackettio#4]
below is log from addons, don't why it keep repeat. and the movies keep loading, playing , loading ,playing.

Thanks regard.

03/01/2024
12:58:59 AM
GET /*******************/download/movie/tt0082640/64a30c6e7bbc8be5a519d8ccdb9bfd5e4835a284
03/01/2024
12:58:59 AM
tt0082640 : get files ...
03/01/2024
12:59:02 AM
tt0082640 : 3 files found
03/01/2024
12:59:06 AM
GET /*******************/download/movie/tt0082640/64a30c6e7bbc8be5a519d8ccdb9bfd5e4835a284
03/01/2024
12:59:10 AM
GET /*******************/download/movie/tt0082640/64a30c6e7bbc8be5a519d8ccdb9bfd5e4835a284
03/01/2024
12:59:11 AM
GET /*******************/download/movie/tt0082640/64a30c6e7bbc8be5a519d8ccdb9bfd5e4835a284
03/01/2024
12:59:11 AM
GET /*******************/download/movie/tt0082640/64a30c6e7bbc8be5a519d8ccdb9bfd5e4835a284
03/01/2024
12:59:50 AM
GET /*******************/download/movie/tt0082640/64a30c6e7bbc8be5a519d8ccdb9bfd5e4835a284
03/01/2024
12:59:50 AM
GET /*******************/download/movie/tt0082640/64a30c6e7bbc8be5a519d8ccdb9bfd5e4835a284
03/01/2024
01:00:04 AM
GET /*******************/download/movie/tt0082640/64a30c6e7bbc8be5a519d8ccdb9bfd5e4835a284
03/01/2024
01:00:06 AM
GET /*******************/download/movie/tt0082640/64a30c6e7bbc8be5a519d8ccdb9bfd5e4835a284

**Comment by arvida42** [comment]
It seems like there might be an issue with the RD server, causing the video to start and stop unexpectedly. In this case, the addon itself isn't at fault.

**Comment by ericvlog** [comment]
because I only have Real-debrid, but same movies and same size I play with torrentio no problem, but jackettio it keeps buffer and loading.

2024-03-01T11:57:50.602634754Z tt14230458 : RD : Cannot read properties of undefined (reading 'reduce')
2024-03-01T11:58:00.952352528Z HEAD /*******************/download/movie/tt14230458/0b1e88ee5f41f26a7782d85f9d84180533f6da17
2024-03-01T11:58:00.975418063Z GET /*******************/download/movie/tt14230458/0b1e88ee5f41f26a7782d85f9d84180533f6da17
2024-03-01T11:58:02.144733158Z GET /*******************/download/movie/tt14230458/0b1e88ee5f41f26a7782d85f9d84180533f6da17
2024-03-01T11:58:05.406688256Z GET /*******************/download/movie/tt14230458/0b1e88ee5f41f26a7782d85f9d84180533f6da17
