### ISSUE TITLE
Add Torbox and Premiumize

### ISSUE THREAD

**Issue by Markodingo** [arvida42/jackettio#40]
As everyone knows, RealDebrid is practically dead, and this is a very painful moment for us… But the other problem looming on the horizon is that both AllDebrid and Debrid-Link are French companies, and it’s only a matter of time before they suffer the same fate as RD. So, if you could add Torbox and Premiumize as debriders, it would be really great ! Thanks you again for amazing work!

**Comment by arvida42** [comment]
Did you know that these two services host all their servers in the EU? They operate similarly to DL, RD, and AD. The company's location isn’t a significant factor.

The hype around Torbox is largely fueled by affiliates promoting a service that often underdelivers, just to earn a few free days of usage. Unfortunately, this highlights the influence of misleading promoters who prioritize personal gain over integrity.

Premiumize will be added soon! It's a well-know service.

**Comment by reddit-reaper** [comment]
@arvida42 hi, can you message me on telegram or email regarding premiumize :) it's so i can give you a premiumize benefit 

Telegram: @reddit_reapercody
Email: redditreaper86@gmail.com

**Comment by arvida42** [comment]
Premiumize added

**Comment by Beingjustinroyfernandes** [comment]
in jackittio 1.6.2 premiumize option is not avaliable

**Comment by Beingjustinroyfernandes** [comment]
in jackittio 1.6.2 premiumize option is not avaliable
