### ISSUE TITLE
Jackettio docker won't start, log: undefined:0 and SQLITE_CANTOPEN

### ISSUE THREAD

**Issue by sandriser** [arvida42/jackettio#8]
Trying to run docker locally per instructions and got stuck after creating container.
It just stops on start and exits.

```
Started addon jackettio v1.1.6

Server listen at: http://localhost:4000

───────────────────────────────────────

undefined:0

[Error: SQLITE_CANTOPEN: unable to open database file

Emitted 'error' event on Database instance at:

] {

  errno: 14,

  code: 'SQLITE_CANTOPEN'

}

```

**Comment by arvida42** [comment]
I think you use the "Manual installation with Docker image" method.

When mounting the /data directory from the host filesystem, ensure that the container has sufficient permissions to write to it.

The alternative solution is to use a docker volume.
```
docker volume create jackettio_data
docker run --env-file .env -v jackettio_data:/data -e DATA_FOLDER=/data --name jackettio -p 4000:4000 -d arvida42/jackettio:latest
```

**Comment by sandriser** [comment]
That was it!

Created volume and it works now :) 

You are amazingly fast.

Issue solved, thank you.
