### ISSUE TITLE
Can Premiumize be added as a debrid provider?

### ISSUE THREAD

**Issue by 4KFTW** [arvida42/jackettio#9]

**Comment by Beingjustinroyfernandes** [comment]
Hi @arvida42 I currently have a Premiumize API key and am trying to add the Jackettio v1.3.0 addon in my Stremio account. However, I am not seeing an option to integrate Premiumize within the addon. Is there anything you could suggest or assist with to help me add Premiumize support in Stremio via the Jackettio addon?

any update on adding premiumize api option in addon ?

**Comment by Beingjustinroyfernandes** [comment]
@arvida42 any update..??

**Comment by Beingjustinroyfernandes** [comment]
@arvida42  any update..?

**Comment by victorgveloso** [comment]
+1 for this. RD is over. AD and DL might follow along. Premiumize and TorBox are the most logical alternatives.
